### ISSUE TITLE
'Chord' object has no attribute 'upload'

### ISSUE THREAD

**Issue by NGL-A** [shahinrostami/plotapi#48]
As stated [here](https://plotapi.com/docs/api-for-coders/uploading-to-cloud/#interactive-html) I'm trying to upload my project, but whenever I run:

```
from plotapi import Chord 

matrix = [
    [0, 5, 6, 4, 7, 4],
    [5, 0, 5, 4, 6, 5],
    [6, 5, 0, 4, 5, 5],
    [4, 4, 4, 0, 5, 5],
    [7, 6, 5, 5, 0, 4],
    [4, 5, 5, 5, 4, 0],
]

names = ["Action", "Adventure", "Comedy", "Drama", "Fantasy", "Thriller"]

project = Chord(matrix, names).upload(name="My Visualization", public=True)
```

I get
`AttributeError: 'Chord' object has no attribute 'upload'`

Any suggestions?

**Comment by shahinrostami** [comment]
Hello @NGL-A!

You may be on an older version of the `plotapi` package, i.e. a version which didn't have the `upload` feature.

Can you check your version? The current version is `6.2.3` both on PyPi and coda-forge. 

You could also drop by our Discord for help over chat https://discord.polyra.com

**Comment by NGL-A** [comment]
Version is indeed 6.2.3, so I don't really have a clue on what's wrong.
I'll jump into Discord
